### ISSUE TITLE
reduce resolution in geojson

### ISSUE THREAD

**Issue by dfolch** [co-ncrn/acs_viz#2]
The geojson files have very high spatial resolution, which impacts load times. These can be reduced with [mapshaper](https://github.com/mbloch/mapshaper); which has a command line tool that could be called from python. The goal is to simplify the geometries, but not so much that they look weird when zoomed in to three or four tracts on the screen. We can also think about reducing the precision of the lat/lons as some have a bunch of trailing 9s; not sure if that is possible in mapshaper.

None of these changes should be made to the shapefiles.

**Comment by geoss** [comment]
Just add some detail.  Use the command line mapshaper tool.  The aim is to write a script that takes the existing geojson files and runs them through map shaper via `os.system('mapshaper ...')`

**Comment by beckymasond** [comment]
New json maps are simplified version of former geojson maps, at 50% reduction in removable vertices. Files in repository should be correct but website may not reflect this/rebuild until data is moved to LFS.
