### ISSUE TITLE
geojson attribute rounding

### ISSUE THREAD

**Issue by dfolch** [co-ncrn/acs_viz#3]
The ratio and proportion values in the geojson can be rounded to 3 decimal places reduce load times. This change should not be made to the CSVs.

**Comment by beckymasond** [comment]
It looks like I already have it set to round to 3 decimals for the ratio and proportion values. If there are exceptions to this that you've found, please let me know and I'll fix them.

**Comment by dfolch** [comment]
Sorry about that, the attributes are rounded already. I was distracted by the extra lat/lon digits referenced in #2.
