### ISSUE TITLE
mismatched attributes

### ISSUE THREAD

**Issue by dfolch** [co-ncrn/acs_viz#4]
In the [Charlotte transportation page](https://co-ncrn.github.io/msa_data/16740/16740_trans.html) the attribute headers on the regions and tracts do not match. This issue may be affecting other pages too.

**Comment by beckymasond** [comment]
My mistake here was that I uploaded different geojson files for each region scenario but only one tract file per MSA. That same tract file is being used for every page. Somehow I overlooked that although the tracts are the same each time, the data is not! I'll add tract files for each scenario to each MSA and then this should be fixed. Good catch.

**Comment by beckymasond** [comment]
I uploaded to scenario tract geojsons and revised the html to display them. The correction may not be visible on the webpage until I finish migrating the data to the large-capacity storage.
